### ISSUE TITLE
MissingMethodException on DictionaryWrapper

### ISSUE THREAD

**Issue by PhilipDaniels** [loresoft/EntityChange#2]
Do you have any idea what would cause this? Sorry I cannot reproduce easily at the moment.

Version:
    <package id="EntityChange" version="2.1.0.16" targetFramework="net45" />

Exception:
```
MissingMethodException - Constructor on type 'EntityChange.DictionaryWrapper`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Newtonsoft.Json.Linq.JToken, Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed]]' not found.
||   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
||   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
||   at System.Activator.CreateInstance(Type type, Object[] args)
||   at EntityChange.EntityComparer.CompareGenericDictionary(Object original, Object current, Type keyType, Type elementType)
||   at EntityChange.EntityComparer.CompareType(Type type, Object original, Object current, IMemberOptions options)
||   at EntityChange.EntityComparer.CompareByKey[T](T originalDictionary, T currentDictionary, Func`2 keysFactory, Func`3 valueFactory)
||   at EntityChange.EntityComparer.CompareGenericDictionary(Object original, Object current, Type keyType, Type elementType)
||   at EntityChange.EntityComparer.CompareType(Type type, Object original, Object current, IMemberOptions options)
||   at EntityChange.EntityComparer.CompareObject(Type type, Object original, Object current)
||   at EntityChange.EntityComparer.CompareType(Type type, Object original, Object current, IMemberOptions options)
||   at EntityChange.EntityComparer.Compare[TEntity](TEntity original, TEntity current)

```

**Comment by pwelter34** [comment]
can't reproduce.  feel free to reopen if you can create a failing test case
